service: SLS-20240222
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

  functions: 
    api:
      handler: index.handler
      event:
      - httpApi:
        method: get
        path: /

plugins:
  - serverless-offline